import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,SlidersHorizontal,Scale,Heart,X,ChevronDown,Download,MapPin,IndianRupee}from'lucide-react';import{EVS,STATES}from'./data';import'./style.css';
const money=n=>'₹'+Math.round(n).toLocaleString('en-IN');const uniq=(a,k)=>[...new Set(a.map(x=>x[k]))];const score=(v)=>Math.round(Math.min(v.rangeKm/300,1)*35+Math.min(v.powerKw/30,1)*20+Math.min(v.topSpeed/160,1)*15+Math.min(v.batteryKwh/12,1)*15+10+5);
function App(){const[brand,setBrand]=useState('All'),[state,setState]=useState('All India'),[q,setQ]=useState(''),[max,setMax]=useState(5000000),[minR,setMinR]=useState(0),[type,setType]=useState('All'),[sort,setSort]=useState('score'),[sel,setSel]=useState(null),[compare,setCompare]=useState([]),[tab,setTab]=useState('discover');
const brands=uniq(EVS,'brand');const filtered=useMemo(()=>EVS.filter(v=>(brand==='All'||v.brand===brand)&&(state==='All India'||v.state===state)&&v.onRoad<=max&&v.rangeKm>=minR&&(!q||`${v.brand} ${v.model} ${v.variant}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='score'?score(b)-score(a):sort==='price'?a.onRoad-b.onRoad:sort==='range'?b.rangeKm-a.rangeKm:b.topSpeed-a.topSpeed),[brand,state,q,max,minR,sort]);
const toggle=v=>setCompare(c=>c.some(x=>x.brand===v.brand&&x.model===v.model&&x.state===v.state)?c.filter(x=>x!==v):c.length<4?[...c,v]:c);
return <main><header><div><div className="eyebrow">VERSION 3 • INDIA EV ATLAS</div><h1>EV Atlas <span>⚡</span></h1><p>Every brand. Every state. Every important EV specification — with state-wise indicative on-road pricing.</p></div><div className="stat"><b>{brands.length}+</b><span>brands indexed</span><b>{uniq(EVS,'model').length}+</b><span>models indexed</span></div></header>
<nav><button className={tab==='discover'?'on':''}onClick={()=>setTab('discover')}>Discover</button><button className={tab==='compare'?'on':''}onClick={()=>setTab('compare')}>Compare {compare.length?`(${compare.length})`:''}</button><button className={tab==='states'?'on':''}onClick={()=>setTab('states')}>State pricing</button></nav>
{tab==='discover'&&<><section className="filters"><div><label>Brand</label><select value={brand}onChange={e=>setBrand(e.target.value)}><option>All</option>{brands.map(x=><option>{x}</option>)}</select></div><div><label>State</label><select value={state}onChange={e=>setState(e.target.value)}><option>All India</option>{STATES.map(x=><option>{x}</option>)}</select></div><div><label>Max on-road</label><input type="number" value={max}onChange={e=>setMax(+e.target.value||0)}/></div><div><label>Min range</label><input type="number" value={minR}onChange={e=>setMinR(+e.target.value||0)}/></div><div className="wide"><label>Search</label><div className="search"><Search size={16}/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search brand, model or variant"/></div></div><div><label>Sort</label><select value={sort}onChange={e=>setSort(e.target.value)}><option value="score">Best overall</option><option value="price">Lowest on-road</option><option value="range">Longest range</option><option value="speed">Highest speed</option></select></div></section>
<div className="summary"><b>{filtered.length.toLocaleString()}</b> state-variant records match <span>• Prices are indicative and must be verified with the dealer.</span></div>
<section className="grid">{filtered.slice(0,120).map((v,i)=><article className="card"key={i}onClick={()=>setSel(v)}><div className="top"><div><small>{v.brand}</small><h2>{v.model}</h2><span>{v.variant}</span></div><button className={compare.includes(v)?'active':''}onClick={e=>{e.stopPropagation();toggle(v)}}><Scale size={17}/></button></div><div className="price">{money(v.onRoad)}<em> on-road • {v.state}</em></div><div className="spec"><b>{v.rangeKm} km</b><b>{v.batteryKwh} kWh</b><b>{v.topSpeed} km/h</b><b>{v.powerKw} kW</b></div><div className="micro"><span>Motor: {v.motor}</span><span>Charging: {v.chargingH} h</span><span>Battery: {v.chemistry}</span><span>Score: {score(v)}/100</span></div></article>)}</section></>}
{tab==='compare'&&<section className="compare"><h2>Side-by-side comparison</h2>{compare.length?<div className="compareTable">{compare.map(v=><div className="compareCol"><b>{v.brand} {v.model}</b><strong>{money(v.onRoad)}</strong>{[['State',v.state],['Range',v.rangeKm+' km'],['Battery',v.batteryKwh+' kWh'],['Power',v.powerKw+' kW'],['Top speed',v.topSpeed+' km/h'],['Chemistry',v.chemistry],['Charging',v.chargingH+' h'],['Fast charge',v.fastCharge],['Motor',v.motor],['Kerb weight',v.kerbKg+' kg'],['Seat',v.seatMm+' mm'],['Ground clearance',v.groundMm+' mm'],['Boot',v.bootL+' L'],['Brakes',v.frontBrake+' / '+v.rearBrake],['ABS/CBS',v.abs],['Suspension',v.suspension],['Modes',v.modes],['Connectivity',v.connectivity],['Navigation',v.navigation],['GPS',v.gps],['OTA',v.ota],['Vehicle warranty',v.warranty],['Battery warranty',v.batteryWarranty]].map(x=><p><span>{x[0]}</span><b>{x[1]}</b></p>)}<button onClick={()=>toggle(v)}>Remove</button></div>)}</div>:<div className="empty">Select vehicles with the comparison button.</div>}</section>}
{tab==='states'&&<section className="states"><h2>India state pricing</h2><p>Choose a brand/model below to inspect indicative on-road pricing across every state.</p><select onChange={e=>{const[vb,vm]=e.target.value.split('|');setBrand(vb);setQ(vm);setTab('discover')}}><option>Choose a vehicle…</option>{uniq(EVS,'brand').flatMap(b=>uniq(EVS.filter(v=>v.brand===b),'model').map(m=><option value={b+'|'+m}>{b} {m}</option>))}</select><div className="stategrid">{STATES.map(s=>{const vals=EVS.filter(v=>v.state===s&&(brand==='All'||v.brand===brand)&&(!q||v.model.toLowerCase().includes(q.toLowerCase())));return <div><MapPin size={14}/><b>{s}</b><span>{vals.length?money(vals[0].onRoad):'—'}</span></div>})}</div></section>}
{sel&&<div className="modal"onClick={()=>setSel(null)}><div className="detail"onClick={e=>e.stopPropagation()}><button className="close"onClick={()=>setSel(null)}><X/></button><small>{sel.brand}</small><h2>{sel.model}</h2><p>{sel.variant} • {sel.state}</p><h3>{money(sel.onRoad)}</h3><div className="allSpecs">{Object.entries(sel).filter(([k])=>!['brand','model','variant','state','exShowroom','onRoad','source','updated'].includes(k)).map(([k,v])=><div><span>{k.replace(/([A-Z])/g,' $1')}</span><b>{String(v)}</b></div>)}</div><p className="note">{sel.source}. Last dataset update: {sel.updated}.</p><button className="primary"onClick={()=>toggle(sel)}>{compare.includes(sel)?'Remove from comparison':'Add to comparison'}</button></div></div>}
<footer>EV Atlas V3 • Designed for mobile, tablet and desktop • Research data requires verification.</footer></main>}
createRoot(document.getElementById('root')).render(<App/>);